### ISSUE TITLE
Can not generate forecast in Agenda view?

### ISSUE THREAD

**Issue by cryoguy** [ruediger/weather-metno-el#13]
Did anybody report this issue?  Metno can not intergrate with Agenda View. It does populate the forecast in "weather" buffer though.  I had the same issue with the previouse version.

Thanks for the great work!

Tony

**Comment by cryoguy** [comment]
Also, I have to disabled mode line for it to show in modeline, but fail to update.  stay with [XoC 0.0mm X%]  , any thoughts?

Thanks again.

Tony

**Comment by ruediger** [comment]
Unfortunately it won't display the weather in the agenda if it has no data. It will populate the data and should work after reloading it (press "g" in the agenda buffer). The modeline seems to indicate that it only had a precipitation value (0.0 mm) for that time.
