### ISSUE TITLE
Info: Emacs 25 does not support ImageMagick7?

### ISSUE THREAD

**Issue by torgeir** [ruediger/weather-metno-el#14]
If anyone else comes looking;

I've recently been getting these 

![https://d3vv6lp55qjaqc.cloudfront.net/items/0G1W451i061a442F1K0V/Image%202017-03-12%20at%208.29.49%20AM.public.png?X-CloudApp-Visitor-Id=5102c944a369d2eb3e4cef97298683d9&v=b6097c54](https://d3vv6lp55qjaqc.cloudfront.net/items/0G1W451i061a442F1K0V/Image%202017-03-12%20at%208.29.49%20AM.public.png?X-CloudApp-Visitor-Id=5102c944a369d2eb3e4cef97298683d9&v=b6097c54)

which seem to be because [emacs 25 does not yet support imagemagick 7](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=25967)

![https://d3vv6lp55qjaqc.cloudfront.net/items/3e1z3v1y3P272q0z3R0W/Image%202017-03-12%20at%208.34.01%20AM.public.png?X-CloudApp-Visitor-Id=5102c944a369d2eb3e4cef97298683d9&v=de21287d](https://d3vv6lp55qjaqc.cloudfront.net/items/3e1z3v1y3P272q0z3R0W/Image%202017-03-12%20at%208.34.01%20AM.public.png?X-CloudApp-Visitor-Id=5102c944a369d2eb3e4cef97298683d9&v=de21287d)

Disabling these two makes it work again

```
(setq ...
  ;; weather-metno-use-imagemagick t
  ;; weather-metno-get-image-props '(:width 20 :height 20 :ascent center)
)
```

**Comment by ruediger** [comment]
You'll need Emacs compiled with ImageMagick support for weather-metno to support it. `weather-metno-use-imagemagick` should be automatically initialized correctly if you have imagemagick support. If not it won't work to force it to t.

**Comment by torgeir** [comment]
Yeah, this was merely for information. Been running with the homebrew compiled emacs 24 with imagemagick for a while, but [after upgrading to 25, the compile flag `brew install emacs ... --with-imagemagick` was silently failing for imagemagick 7](https://github.com/Homebrew/homebrew-core/blob/master/Formula/emacs.rb#L42-L44), and has since been disabled.
