### ISSUE TITLE
Error in processing : XML: System ID missing

### ISSUE THREAD

**Issue by unixbhaskar** [ruediger/weather-metno-el#15]
While trying to use **M-x weather-metno-forecast**  The title text printed on the minibuffer....

"error in process filter: xml-parse-dtd: XML: Missing System ID" ...this is what I got.

Bemused. Kindly shed some light.

PS: Given the longitude and latitude and name for the location .

**Comment by anoduck** [comment]
@unixbhaskar Was this ever resolved? Experiencing the exact same issue.

@ruediger Just for prosperity, here is my debug output.

```elisp
  xml-parse-tag-1(nil nil)
  xml--parse-buffer(nil nil)
  xml-parse-region(378 23668)
  #f(compiled-function (status callback lat lon msl) #<bytecode 0x16628d094f6b34dd>)((:redirect "https://api.met.no" :peer (:certificates ((:version 3 :serial-number "00:c9:5f:71:08:ed:fd:53:da:b6:88:d7:6a:ea:8d:7b:19" :issuer "C=NL,O=GEANT Vereniging,CN=GEANT OV RSA CA 4" :valid-from "2022-04-05" :valid-to "2023-04-05" :subject "C=NO,L=Oslo,O=Meteorologisk institutt,CN=*.api.met..." :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:31:39:5f:12:ad:c3:a1:c2:6b:7a:0c:1a:88:52:9a:..." :certificate-id "sha1:a6:35:9f:6b:6b:3a:ae:c0:ad:32:08:04:e0:d7:81:..." :pem "-----BEGIN CERTIFICATE-----\nMIIHUDCCBTigAwIBAgIRAM...") (:version 3 :serial-number "00:da:43:bd:13:9b:d2:58:bb:4d:d6:1c:ac:c4:f3:db:e0" :issuer "C=US,ST=New Jersey,L=Jersey City,O=The USERTRUST N..." :valid-from "2020-02-18" :valid-to "2033-05-01" :subject "C=NL,O=GEANT Vereniging,CN=GEANT OV RSA CA 4" :public-key-algorithm "RSA" :certificate-security-level "High" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:e2:7f:be:76:08:b0:84:8e:c2:88:3d:3d:f8:e3:58:..." :certificate-id "sha1:c2:82:6e:26:6d:74:05:d3:4e:f8:97:62:63:6a:e4:..." :pem "-----BEGIN CERTIFICATE-----\nMIIG5TCCBM2gAwIBAgIRAN...") (:version 3 :serial-number "39:72:44:3a:f9:22:b7:51:d7:d3:6c:10:dd:31:35:95" :issuer "C=GB,ST=Greater Manchester,L=Salford,O=Comodo CA L..." :valid-from "2019-03-12" :valid-to "2028-12-31" :subject "C=US,ST=New Jersey,L=Jersey City,O=The USERTRUST N..." :public-key-algorithm "RSA" :certificate-security-level "High" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:c8:95:13:68:01:97:28:0a:2c:55:c3:fc:d3:90:f5:..." :certificate-id "sha1:d8:9e:3b:d4:3d:5d:90:9b:47:a1:89:77:aa:9d:5c:..." :pem "-----BEGIN CERTIFICATE-----\nMIIFgTCCBGmgAwIBAgIQOX...")) :certificate (:version 3 :serial-number "00:c9:5f:71:08:ed:fd:53:da:b6:88:d7:6a:ea:8d:7b:19" :issuer "C=NL,O=GEANT Vereniging,CN=GEANT OV RSA CA 4" :valid-from "2022-04-05" :valid-to "2023-04-05" :subject "C=NO,L=Oslo,O=Meteorologisk institutt,CN=*.api.met..." :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:31:39:5f:12:ad:c3:a1:c2:6b:7a:0c:1a:88:52:9a:..." :certificate-id "sha1:a6:35:9f:6b:6b:3a:ae:c0:ad:32:08:04:e0:d7:81:..." :pem "-----BEGIN CERTIFICATE-----\nMIIHUDCCBTigAwIBAgIRAM...") :key-exchange "ECDHE-RSA" :protocol "TLS1.3" :cipher "AES-256-GCM" :mac "AEAD" :encrypt-then-mac nil)) #f(compiled-function (lat lon msl raw-xml data) #<bytecode -0x1c195bc361666d44>) 33.4826 -117.55496 138.0)
  apply(#f(compiled-function (status callback lat lon msl) #<bytecode 0x16628d094f6b34dd>) ((:redirect "https://api.met.no" :peer (:certificates ((:version 3 :serial-number "00:c9:5f:71:08:ed:fd:53:da:b6:88:d7:6a:ea:8d:7b:19" :issuer "C=NL,O=GEANT Vereniging,CN=GEANT OV RSA CA 4" :valid-from "2022-04-05" :valid-to "2023-04-05" :subject "C=NO,L=Oslo,O=Meteorologisk institutt,CN=*.api.met..." :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:31:39:5f:12:ad:c3:a1:c2:6b:7a:0c:1a:88:52:9a:..." :certificate-id "sha1:a6:35:9f:6b:6b:3a:ae:c0:ad:32:08:04:e0:d7:81:..." :pem "-----BEGIN CERTIFICATE-----\nMIIHUDCCBTigAwIBAgIRAM...") (:version 3 :serial-number "00:da:43:bd:13:9b:d2:58:bb:4d:d6:1c:ac:c4:f3:db:e0" :issuer "C=US,ST=New Jersey,L=Jersey City,O=The USERTRUST N..." :valid-from "2020-02-18" :valid-to "2033-05-01" :subject "C=NL,O=GEANT Vereniging,CN=GEANT OV RSA CA 4" :public-key-algorithm "RSA" :certificate-security-level "High" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:e2:7f:be:76:08:b0:84:8e:c2:88:3d:3d:f8:e3:58:..." :certificate-id "sha1:c2:82:6e:26:6d:74:05:d3:4e:f8:97:62:63:6a:e4:..." :pem "-----BEGIN CERTIFICATE-----\nMIIG5TCCBM2gAwIBAgIRAN...") (:version 3 :serial-number "39:72:44:3a:f9:22:b7:51:d7:d3:6c:10:dd:31:35:95" :issuer "C=GB,ST=Greater Manchester,L=Salford,O=Comodo CA L..." :valid-from "2019-03-12" :valid-to "2028-12-31" :subject "C=US,ST=New Jersey,L=Jersey City,O=The USERTRUST N..." :public-key-algorithm "RSA" :certificate-security-level "High" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:c8:95:13:68:01:97:28:0a:2c:55:c3:fc:d3:90:f5:..." :certificate-id "sha1:d8:9e:3b:d4:3d:5d:90:9b:47:a1:89:77:aa:9d:5c:..." :pem "-----BEGIN CERTIFICATE-----\nMIIFgTCCBGmgAwIBAgIQOX...")) :certificate (:version 3 :serial-number "00:c9:5f:71:08:ed:fd:53:da:b6:88:d7:6a:ea:8d:7b:19" :issuer "C=NL,O=GEANT Vereniging,CN=GEANT OV RSA CA 4" :valid-from "2022-04-05" :valid-to "2023-04-05" :subject "C=NO,L=Oslo,O=Meteorologisk institutt,CN=*.api.met..." :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:31:39:5f:12:ad:c3:a1:c2:6b:7a:0c:1a:88:52:9a:..." :certificate-id "sha1:a6:35:9f:6b:6b:3a:ae:c0:ad:32:08:04:e0:d7:81:..." :pem "-----BEGIN CERTIFICATE-----\nMIIHUDCCBTigAwIBAgIRAM...") :key-exchange "ECDHE-RSA" :protocol "TLS1.3" :cipher "AES-256-GCM" :mac "AEAD" :encrypt-then-mac nil)) #f(compiled-function (lat lon msl raw-xml data) #<bytecode -0x1c195bc361666d44>) 33.4826 -117.55496 138.0))
  url-http-activate-callback()
  url-http-wait-for-headers-change-function(1 397 396)
  #f(compiled-function (proc data) #<bytecode 0x9d23be99a419995>)(#<process api.met.no<1>> "HTTP/1.1 304 Not Modified\15\nServer: nginx/1.18.0 (U...")
  apply(#f(compiled-function (proc data) #<bytecode 0x9d23be99a419995>) (#<process api.met.no<1>> "HTTP/1.1 304 Not Modified\15\nServer: nginx/1.18.0 (U..."))
  #f(compiled-function (f &rest args) #<bytecode 0xda0ecf88d1a06ce>)(#f(compiled-function (proc data) #<bytecode 0x9d23be99a419995>) #<process api.met.no<1>> "HTTP/1.1 304 Not Modified\15\nServer: nginx/1.18.0 (U...")
  apply(#f(compiled-function (f &rest args) #<bytecode 0xda0ecf88d1a06ce>) #f(compiled-function (proc data) #<bytecode 0x9d23be99a419995>) (#<process api.met.no<1>> "HTTP/1.1 304 Not Modified\15\nServer: nginx/1.18.0 (U..."))
  url-http-generic-filter(#<process api.met.no<1>> "HTTP/1.1 304 Not Modified\15\nServer: nginx/1.18.0 (U...")
```

**Comment by unixbhaskar** [comment]
> @unixbhaskar Was this ever resolved? Experiencing the exact same issue.
> 
> 
> 
> @ruediger Just for prosperity, here is my debug output.
> 
> 
> 
> ```elisp
> 
>   xml-parse-tag-1(nil nil)
> 
>   xml--parse-buffer(nil nil)
> 
>   xml-parse-region(378 23668)
> 
>   #f(compiled-function (status callback lat lon msl) #<bytecode 0x16628d094f6b34dd>)((:redirect "https://api.met.no" :peer (:certificates ((:version 3 :serial-number "00:c9:5f:71:08:ed:fd:53:da:b6:88:d7:6a:ea:8d:7b:19" :issuer "C=NL,O=GEANT Vereniging,CN=GEANT OV RSA CA 4" :valid-from "2022-04-05" :valid-to "2023-04-05" :subject "C=NO,L=Oslo,O=Meteorologisk institutt,CN=*.api.met..." :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:31:39:5f:12:ad:c3:a1:c2:6b:7a:0c:1a:88:52:9a:..." :certificate-id "sha1:a6:35:9f:6b:6b:3a:ae:c0:ad:32:08:04:e0:d7:81:..." :pem "-----BEGIN CERTIFICATE-----\nMIIHUDCCBTigAwIBAgIRAM...") (:version 3 :serial-number "00:da:43:bd:13:9b:d2:58:bb:4d:d6:1c:ac:c4:f3:db:e0" :issuer "C=US,ST=New Jersey,L=Jersey City,O=The USERTRUST N..." :valid-from "2020-02-18" :valid-to "2033-05-01" :subject "C=NL,O=GEANT Vereniging,CN=GEANT OV RSA CA 4" :public-key-algorithm "RSA" :certificate-security-level "High" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:e2:7f:be:76:08:b0:84:8e:c2:88:3d:3d:f8:e3:58:..." :certificate-id "sha1:c2:82:6e:26:6d:74:05:d3:4e:f8:97:62:63:6a:e4:..." :pem "-----BEGIN CERTIFICATE-----\nMIIG5TCCBM2gAwIBAgIRAN...") (:version 3 :serial-number "39:72:44:3a:f9:22:b7:51:d7:d3:6c:10:dd:31:35:95" :issuer "C=GB,ST=Greater Manchester,L=Salford,O=Comodo CA L..." :valid-from "2019-03-12" :valid-to "2028-12-31" :subject "C=US,ST=New Jersey,L=Jersey City,O=The USERTRUST N..." :public-key-algorithm "RSA" :certificate-security-level "High" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:c8:95:13:68:01:97:28:0a:2c:55:c3:fc:d3:90:f5:..." :certificate-id "sha1:d8:9e:3b:d4:3d:5d:90:9b:47:a1:89:77:aa:9d:5c:..." :pem "-----BEGIN CERTIFICATE-----\nMIIFgTCCBGmgAwIBAgIQOX...")) :certificate (:version 3 :serial-number "00:c9:5f:71:08:ed:fd:53:da:b6:88:d7:6a:ea:8d:7b:19" :issuer "C=NL,O=GEANT Vereniging,CN=GEANT OV RSA CA 4" :valid-from "2022-04-05" :valid-to "2023-04-05" :subject "C=NO,L=Oslo,O=Meteorologisk institutt,CN=*.api.met..." :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:31:39:5f:12:ad:c3:a1:c2:6b:7a:0c:1a:88:52:9a:..." :certificate-id "sha1:a6:35:9f:6b:6b:3a:ae:c0:ad:32:08:04:e0:d7:81:..." :pem "-----BEGIN CERTIFICATE-----\nMIIHUDCCBTigAwIBAgIRAM...") :key-exchange "ECDHE-RSA" :protocol "TLS1.3" :cipher "AES-256-GCM" :mac "AEAD" :encrypt-then-mac nil)) #f(compiled-function (lat lon msl raw-xml data) #<bytecode -0x1c195bc361666d44>) 33.4826 -117.55496 138.0)
> 
>   apply(#f(compiled-function (status callback lat lon msl) #<bytecode 0x16628d094f6b34dd>) ((:redirect "https://api.met.no" :peer (:certificates ((:version 3 :serial-number "00:c9:5f:71:08:ed:fd:53:da:b6:88:d7:6a:ea:8d:7b:19" :issuer "C=NL,O=GEANT Vereniging,CN=GEANT OV RSA CA 4" :valid-from "2022-04-05" :valid-to "2023-04-05" :subject "C=NO,L=Oslo,O=Meteorologisk institutt,CN=*.api.met..." :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:31:39:5f:12:ad:c3:a1:c2:6b:7a:0c:1a:88:52:9a:..." :certificate-id "sha1:a6:35:9f:6b:6b:3a:ae:c0:ad:32:08:04:e0:d7:81:..." :pem "-----BEGIN CERTIFICATE-----\nMIIHUDCCBTigAwIBAgIRAM...") (:version 3 :serial-number "00:da:43:bd:13:9b:d2:58:bb:4d:d6:1c:ac:c4:f3:db:e0" :issuer "C=US,ST=New Jersey,L=Jersey City,O=The USERTRUST N..." :valid-from "2020-02-18" :valid-to "2033-05-01" :subject "C=NL,O=GEANT Vereniging,CN=GEANT OV RSA CA 4" :public-key-algorithm "RSA" :certificate-security-level "High" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:e2:7f:be:76:08:b0:84:8e:c2:88:3d:3d:f8:e3:58:..." :certificate-id "sha1:c2:82:6e:26:6d:74:05:d3:4e:f8:97:62:63:6a:e4:..." :pem "-----BEGIN CERTIFICATE-----\nMIIG5TCCBM2gAwIBAgIRAN...") (:version 3 :serial-number "39:72:44:3a:f9:22:b7:51:d7:d3:6c:10:dd:31:35:95" :issuer "C=GB,ST=Greater Manchester,L=Salford,O=Comodo CA L..." :valid-from "2019-03-12" :valid-to "2028-12-31" :subject "C=US,ST=New Jersey,L=Jersey City,O=The USERTRUST N..." :public-key-algorithm "RSA" :certificate-security-level "High" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:c8:95:13:68:01:97:28:0a:2c:55:c3:fc:d3:90:f5:..." :certificate-id "sha1:d8:9e:3b:d4:3d:5d:90:9b:47:a1:89:77:aa:9d:5c:..." :pem "-----BEGIN CERTIFICATE-----\nMIIFgTCCBGmgAwIBAgIQOX...")) :certificate (:version 3 :serial-number "00:c9:5f:71:08:ed:fd:53:da:b6:88:d7:6a:ea:8d:7b:19" :issuer "C=NL,O=GEANT Vereniging,CN=GEANT OV RSA CA 4" :valid-from "2022-04-05" :valid-to "2023-04-05" :subject "C=NO,L=Oslo,O=Meteorologisk institutt,CN=*.api.met..." :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA384" :public-key-id "sha1:31:39:5f:12:ad:c3:a1:c2:6b:7a:0c:1a:88:52:9a:..." :certificate-id "sha1:a6:35:9f:6b:6b:3a:ae:c0:ad:32:08:04:e0:d7:81:..." :pem "-----BEGIN CERTIFICATE-----\nMIIHUDCCBTigAwIBAgIRAM...") :key-exchange "ECDHE-RSA" :protocol "TLS1.3" :cipher "AES-256-GCM" :mac "AEAD" :encrypt-then-mac nil)) #f(compiled-function (lat lon msl raw-xml data) #<bytecode -0x1c195bc361666d44>) 33.4826 -117.55496 138.0))
> 
>   url-http-activate-callback()
> 
>   url-http-wait-for-headers-change-function(1 397 396)
> 
>   #f(compiled-function (proc data) #<bytecode 0x9d23be99a419995>)(#<process api.met.no<1>> "HTTP/1.1 304 Not Modified\15\nServer: nginx/1.18.0 (U...")
> 
>   apply(#f(compiled-function (proc data) #<bytecode 0x9d23be99a419995>) (#<process api.met.no<1>> "HTTP/1.1 304 Not Modified\15\nServer: nginx/1.18.0 (U..."))
> 
>   #f(compiled-function (f &rest args) #<bytecode 0xda0ecf88d1a06ce>)(#f(compiled-function (proc data) #<bytecode 0x9d23be99a419995>) #<process api.met.no<1>> "HTTP/1.1 304 Not Modified\15\nServer: nginx/1.18.0 (U...")
> 
>   apply(#f(compiled-function (f &rest args) #<bytecode 0xda0ecf88d1a06ce>) #f(compiled-function (proc data) #<bytecode 0x9d23be99a419995>) (#<process api.met.no<1>> "HTTP/1.1 304 Not Modified\15\nServer: nginx/1.18.0 (U..."))
> 
>   url-http-generic-filter(#<process api.met.no<1>> "HTTP/1.1 304 Not Modified\15\nServer: nginx/1.18.0 (U...")
> 
> ```

Nope,I have given up on it and moved on.

**Comment by anoduck** [comment]
@unixbhaskar Although, I prefer the European weather models, I have followed suit, and will be moving on to a different weather package. Sad to see this project fall into an unmaintained status, doom-modeline still uses it for their status line, and it did provide a lovely interface. 

Thanks for the feedback, Cheers.

**Comment by JAslak** [comment]
I was playing around with the weather-metno--forecast-url and weather-metno--weathericon-url function and typing the results into a browser and found that the url formats are no longer valid.

I noticed that weather-metno--forecast-url would create a url like this: 
http://api.met.no/weatherapi/locationforecast/1.9/?lat=48;lon=16
, but in order for met.no locationforecast web api to return any xml data, the url that needs to be generated so it looks something like this:
http**s**://api.met.no/weatherapi/locationforecast/**2.0**/**classic**?lat=48&lon=16
(note also that the lat and lon variable are separated by & and not ";" )

And regarding weather-metno--weathericon-url, in the weathericon api on met.no it says:

> The icons are not meant to be called on demand _like earlier versions_, but to be downloaded as a gzipped TAR archive and packed with your application. 

So if someone could fix these things, then I think the emacs package will work again.

**Comment by ruediger** [comment]
PR #27 was just merged and should fix the issue. Please test. I no longer use the code, so would be happy to hand over to a new maintainer.
